# Client Type: author

   # Information for connecting to the source content
   serverUsername : '<username>'
   serverPassword : '<password>'
   serverScheme : http
   serverHost : some.other.server
   serverPort : 4502

   deltaContent : true # default for all the paths

   # A reference to the standard set of workflow configuration ids that
   # we want to turn off when working with DAM assets.
   damWorkflows: &ourDamWorkflows
     - /conf/global/settings/workflow/launcher/config/dam_xmp_writeback
     - /conf/global/settings/workflow/launcher/config/update_asset_create
     - /conf/global/settings/workflow/launcher/config/update_asset_create_without_DM
     - /conf/global/settings/workflow/launcher/config/update_asset_mod
     - /conf/global/settings/workflow/launcher/config/update_asset_mod_without_DM


   # Each of the paths to include in the copy
   pathConfigurations :
     -
       path : /content/someContent
     -
       path : /content/someOtherContent
       excludePaths: [ someExcludeContent ]
     -
       path : /content/dam/someDamContent
       excludePaths :
         - someContent/someExcludeContent
         - someContent/someOtherExcludeContent
       workflowConfigIds : *ourDamWorkflows
